name: Build Club

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Tag version for the image'
        required: true
        default: 'latest'

jobs:
  offline-club-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone private repository with specific tag
        run: |
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/mkoziy/offline.club.git private-repo
          cd private-repo
          git checkout tags/${{ github.event.inputs.tag_version }} -b build-branch || {
            echo "::error::Tag ${{ github.event.inputs.tag_version }} not found in repository"
            exit 1
          }

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/arm64 --tag ghcr.io/${{ github.repository_owner }}/offline.club:${{ github.event.inputs.tag_version }} --push ./private-repo