name: Setup server

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'

jobs:
  run-ansible:
    runs-on: ubuntu-latest
    env:
      SSH_KEY_PATH: /tmp/ssh_key
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Create inventory file
        run: |
          mkdir -p inventory/${{ github.event.inputs.environment }}
          cat > inventory/${{ github.event.inputs.environment }}/hosts << EOF
          [production]
          prod ansible_host=${{ secrets.PRODUCTION_SSH_HOST }} ansible_user=root
          EOF

      - name: Set up SSH key
        run: echo "${{ secrets.PRODUCTION_SSH_KEY }}" > ${{ env.SSH_KEY_PATH }} && chmod 600 ${{ env.SSH_KEY_PATH }}

      - name: Debug SSH connection
        run: ssh -i ${{ env.SSH_KEY_PATH }} -o StrictHostKeyChecking=no -v ${{ secrets.PRODUCTION_SSH_HOST }} 'echo "Connection successful"'
        continue-on-error: true

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ./inventory/${{ github.event.inputs.environment }}/hosts ./ansible/setup.yml --private-key=${{ env.SSH_KEY_PATH }}
        env:
          ANSIBLE_HOST_KEY_CHECKING: False